version: 2
registries:
  python-index-pypi-python-org-simple:
    type: python-index
    url: https://pypi.python.org/simple/

updates:
- package-ecosystem: pip
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  registries:
  - python-index-pypi-python-org-simple
